Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

            //DEALERS
            Route::group(array("prefix" => "dealers", "as"=>"dealers."), function () {
                Route::get("{id}/copy", array("as"=>"copy", "uses" => "DealerController@copy"));
                Route::get("api/zipcity", array("as"=>"api.zipcity", "uses" => "DealerController@getZipCityJson"));
                Route::any("api/table", array( "as" => "api.table", "uses" => "DealerController@getDatatable"));
                Route::any("api/closurerow", array("as"=>"api.closurerow", "uses" => "DealerController@getClosureRow"));
                Route::any("map", array( "as" => "map", "uses" => "DealerController@map"));
                Route::any("fillnullgps", array( "as" => "map", "uses" => "DealerController@fillNullGps"));
                Route::get("api/table/categories/{dealerid?}", array("as"=>"api.table.categories", "uses"=>"DealerController@getCategoriesDatatable"));
            });
            Route::resource("dealers", "DealerController");
        });
    });
});

Models/Dealer.php
<?php

namespace Dcms\Dealers\Models;

use Dcms\Core\Models\EloquentDefaults;

class Dealer extends EloquentDefaults
{
    protected $connection = 'project';
    protected $table = "dealers";

    public function pages()
    {
        // BelongsToMany belongsToMany(string $related, string $table = null, string $foreignKey = null, string $otherKey = null, string $relation = null)
        return $this->belongsToMany('Dcms\Pages\Models\Pageslanguage', 'dealers_to_pages', 'dealer_id', 'page_id')->withTimestamps();
    }

    public function category()
    {
        return $this->belongsToMany('Dcms\Dealers\Models\Productcategory', 'dealers_to_productcategory', 'dealer_id', 'category_id')->withTimestamps();
    }

    public function openings()
    {
        return $this->hasMany(Opening::class);
    }
}

Http/Controllers/DealerController.php
<?php

namespace Dcms\Dealers\Http\Controllers;

use DB;
use Auth;
use Form;
use View;
use Schema;
use Session;
use DateTime;
use Redirect;
use Validator;
use DataTables;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Dcms\Dealers\Models\Dealer;
use Dcms\Dealers\Models\Closure;
use Dcms\Dealers\Models\Opening;
use Dcms\Dealers\Models\Zipcity;
use Dcms\Dealers\Models\ZipcityNL;
use Dcms\Core\Http\Controllers\BaseController;

class DealerController extends BaseController
{
    public $countries = [];
    public $extendFormTemplate = "";
    public $ColumNames = [];
    public $ColumnNamesDefaults = []; // e.g. checkboxes left blank will result in NULL database value, if this is not what you want, you can set e.g. array('checkbox_name'=>'0');

    public function __construct()
    {
        $this->middleware('permission:dealers-browse')->only('index');
        $this->middleware('permission:dealers-add')->only(['create', 'store']);
        $this->middleware('permission:dealers-edit')->only(['edit', 'update']);
        $this->middleware('permission:dealers-delete')->only('destroy');

        $this->extendformTemplate = null;
        $this->ColumNames = array_merge($this->ColumNames, ['dealer' => 'dealer', 'address' => 'address', 'zip' => 'zip', 'city' => 'city', 'country_id' => 'country_id', 'phone' => 'phone', 'email' => 'email', 'contactemail' => 'contactemail', 'attention'=>'attention', 'website' => 'website']);
        $this->ColumNames = array_merge($this->ColumNames, ['premium'=>'premium','propremium'=>'propremium',  'procenter'=>'procenter', 'tuincenter'=>'tuincenter', 'webshop' => 'webshop', 'code'=>'code', 'code_NL'=>'code_NL', 'naturapy'=>'naturapy', 'naturapypickup'=>'naturapypickup' ,'contactlanguage' => 'contactlanguage' ]);
        $this->ColumnNamesDefaults = array_merge($this->ColumnNamesDefaults, ['country_id' => '1']);
        $this->ColumnNamesDefaults = array_merge($this->ColumnNamesDefaults, [ 'premium'=>'0','propremium'=>'0',  'procenter'=>'0', 'tuincenter'=>'0', 'webshop'=>'0',  'naturapy'=>'0', 'naturapypickup'=>'0']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $filtercolumns = ['dealer' => 'dealer', 'city' => 'city', 'country' => 'country (ISO 3166-2)', 'procenter' => 'pro', 'sector' => 'sector'];
        return View::make('dcms::dealers/index')->with('filtercolumns', $filtercolumns);
    }

    public function map(Request $request)
    {
        $mapMarkers = "";

        if ($request->server("REQUEST_METHOD") == "POST") {
            $SQLDealers = Dealer::where('country_id', 'LIKE', '%');
            if ($request->has('country_id') && $request->get('country_id') > 0) {
                $SQLDealers = Dealer::where('country_id', 'LIKE', $request->get('country_id'));
            }

            $SQLDealers = $SQLDealers->where('id', '>', '0');
            if (strlen($request->get('search')) > 0) {
                $SQLDealers = $SQLDealers->where(function ($query) use ($request) {
                    $query->where('dealer', 'LIKE', $request->get('search'));
                    $query->orWhere('address', 'LIKE', $request->get('search'));
                    $query->orWhere('city', 'LIKE', $request->get('search'));
                });
            }
            if ($request->get('tuincentrum') == 1) {
                $SQLDealers = $SQLDealers->where('tuincenter', '=', '1');
            }
            if ($request->get('procenter') == 1) {
                $SQLDealers = $SQLDealers->where('procenter', '=', '1');
            }
            if ($request->get('premium') == 1) {
                $SQLDealers = $SQLDealers->where('premium', '=', '1');
            }
            if ($request->get('propremium') == 1) {
                $SQLDealers = $SQLDealers->where('propremium', '=', '1');
            }
            if ($request->get('naturapy') == 1) {
                $SQLDealers = $SQLDealers->where('naturapy', '=', '1');
            }
            if ($request->get('naturapypickup') == 1) {
                $SQLDealers = $SQLDealers->where('naturapypickup', '=', '1');
            }
                $SQLDealers = $SQLDealers->whereNotNull('longitude');
                $SQLDealers = $SQLDealers->whereNotNull('latitude');
            $Dealers = $SQLDealers->get();

            if ($Dealers->count() > 0) {
                foreach ($Dealers as $Dealer) {
                    $thisDealer = "";

                    $detaillink = "http://www.dcm-info.be/nl/hobby/verkooppunten/";

                    if ($Dealer->country_id == '2' && $Dealer->procenter == '1') {
                        $detaillink = "http://www.dcm-info.nl/pro/verkooppunten/";
                    } elseif ($Dealer->country_id == '2' && $Dealer->procenter == '0') {
                        $detaillink = "http://www.dcm-info.nl/hobby/verkooppunten/";
                    } elseif ($Dealer->country_id == '3') {
                        $detaillink = "http://www.dcm-info.fr/hobby/points-de-vente/";
                    }

                    $thisDealer = $thisDealer . "<h3><a href='" . $detaillink . $Dealer->id . "/" . Str::slug($Dealer->dealer) . "/' target='_parent'> " . $Dealer->dealer . "</a></h3>";
                    $http = "http";

                    if (intval($Dealer->premium) == 1) {
                        $thisDealer = $thisDealer . "<img src='" . $http . "://www.dcm-info.com/images/dealer/nl/premium.png' alt='Premium' class='premium' />";
                    }
                    if (intval($Dealer->webshop) == "1") {
                        $thisDealer = $thisDealer . "<a href='" . $Dealer->website . "'><img src='" . $http . "://www.dcm-info.com/images/dealer/nl/webshop.png' alt='webshop' class='webshop' /></a>";
                    }
                    $thisDealer .= "<p>";

                    if (strlen(trim($Dealer->address)) > 0) {
                        $thisDealer .= $Dealer->address . "<br />";
                    }

                    if (strlen(trim($Dealer->zip)) > 0) {
                        $thisDealer .= $Dealer->zip . " " . $Dealer->city . "<br />";
                    }

                    if (strlen(trim($Dealer->phone)) > 0) {
                        $thisDealer .= "<i class='far fa-phone'></i> " . $Dealer->phone . "<br />";
                    }
                    //if(strlen(trim($Dealer->fax))>0) 		$thisDealer .= "<i class='far fa-print'></i> " . $Dealer->fax . "<br />" ;
                    if (strlen(trim($Dealer->email)) > 0) {
                        $thisDealer .= "<i class='far fa-envelope'></i> <a href='mailto:" . $Dealer->email . "'>" . $Dealer->email . "</a><br />";
                    }

                    if (strlen($Dealer->website) > 0) {
                        if (strpos($Dealer->website, "http://") >= 0 || strpos($Dealer->website, "https://") >= 0) {
                            $website = $Dealer->website;
                        } else {
                            $website = "http://" . $Dealer->website;
                        }
                        $thisDealer = $thisDealer . "<i class='far fa-laptop'></i> <a href='" . $website . "' target='_blank'> " . str_replace("http://", "", $website) . "</a><br />";
                    } //'end if website check
                    /*'==============================================================================================================================================================*/

                    $thisDealer .= "</p>";
                    $thisDealer .= '<form method="POST" action="/admin/dealers/' . $Dealer->id . '" accept-charset="UTF-8" class="pull-right"> <input name="_token" type="hidden" value="' . csrf_token() . '"> <input name="_method" type="hidden" value="DELETE"><a class="btn btn-xs btn-default" href="/admin/dealers/' . $Dealer->id . '/edit"><i class="far fa-pencil"></i></a><button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="far fa-trash-alt"></i></button></form>';
                    $icon = "gmap_pin1.png";
                    $type = "default";

                    if ($Dealer->premium == 1 && $Dealer->country_id == 1) {
                        $icon = "gmap_pin3.png";
                        $type = "premium";
                    }


                    if ($Dealer->premium == 1 && $Dealer->country_id <> 1) {
                        $icon = "gmap_pin5.png";
                        $type = "extended";
                    }

                    $mapMarkers .=  ",{
                        position: new google.maps.LatLng(" . $Dealer->latitude . ", " . $Dealer->longitude . "),
                        title: '".str_replace("'", "", $Dealer->dealer)."',
                        info: '".str_replace("'", '"', $thisDealer)."',
                        zindex: ". $Dealer->id.",
                        type: '".$type."'
                    }";
                }
                $mapMarkers = substr($mapMarkers, 1);
            }
        }
        // load the view
        return View::make('dcms::dealers/map')->withInput($request->all())->with('mapMarkers', $mapMarkers);
    }

    public function getZipCityJson(Request $request)
    {
        $zipcity = trim($request->get("zipcity"));
        $country_id = trim($request->get("country_id"));

        if ($country_id == "1") {
            return Zipcity::select('postcode as zip', 'gemeente as city', (DB::connection('admin')->table('admin')->raw('CONCAT(postcode, " ", gemeente) AS label')))->where('postcode', 'LIKE', $zipcity . '%')->orwhere('gemeente', 'LIKE', '%' . $zipcity . '%')->get()->toJson();
        } else {

resources/views/dealers/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Dealers</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-map-marker-alt"></i> Dealers</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('dealers-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/dealers/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>
                    <div class="panel filter up">
                        <div class="panel-heading">
                            <h3>Filter <i class="far fa-plus-square right"></i></h3>
                        </div>
                        <div class="panel-body" @if(Session::has('dealerfilter')) style="display:block;" @endif>
                            {!! Form::open(array('url' => 'admin/dealers', 'method' => 'GET')) !!}
                            <div class="form-group" id="filters">
                                <?php
                                if (request()->has('resetfilters') && request()->get('resetfilters') == 'true') {
                                    Session::forget('dealerfilter');
                                }
                                $condition = false;
                                ?>
                                <?php //Session::pull('dealerfilter');?>
                                @if(request()->has('colname') || Session::has('dealerfilter'))
                                @if(request()->has('colname'))
                                <?php
                                Session::put('dealerfilter', request()->all()); //put in a session so the Datatable request can accesss the variables
                                $condition = false;
                                ?>
                                @endif

                                @foreach(Session::get('dealerfilter.colname') as $i => $set_colname)
                                    @if($set_colname != '0')
                                        <?php $condition = true; ?>
                                        <div id="{{$i}}" class="condition">
                                            {!! Form::label('id', 'AND', array('class' => 'form-control left')) !!}
                                            {!! Form::select('colname[]', (array('Filter Column') + $filtercolumns) /*(array('Filter Column') + array_combine(array_values($filtercolumns),$filtercolumns))*/, $set_colname, array('class' => 'form-control left')) !!}
                                            {!! Form::label('id', '=', array('class' => 'form-control left')) !!}
                                            {!! Form::text('colvalue[]', Session::get('dealerfilter.colvalue.'.$i)/*request()->get('colvalue.'.$i)*/, array('class' => 'form-control left')) !!}
                                        </div>
                                    @endif
                                @endforeach
                                @endif
                                @if( (!Session::has('dealerfilter')  && !request()->has('colname')) || $condition == false)
                                    <div id="0" class="condition">
                                        {!! Form::label('id', 'AND', array('class' => 'form-control left')) !!}
                                        {!! Form::select('colname[]', (array('Filter Column') + $filtercolumns) /*(array('Filter Column') + array_combine(array_values($columns),$columns))*/, null, array('class' => 'form-control left')) !!}
                                        {!! Form::label('id', '=', array('class' => 'form-control left')) !!}
                                        {!! Form::text('colvalue[]', '', array('class' => 'form-control left')) !!}
                                    </div>
                                @endif


                                <a class="btn btn-default add-condition" href=""><i class="far fa-plus"></i></a>
                            </div>
                            <div class="btnbar btnbar-left">
                                {!! Form::button('Set Filter', array('class' => 'btn btn-primary', 'type'=>'submit')) !!}
                                <a class="btn btn-default" href="{{url('admin/dealers?resetfilters=true')}}">Reset Filter</a>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>


                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                              <th>Code</th>
                              <th>Dealer</th>
                            <th>City</th>
                            <th>Country</th>
                            <th>Longitude</th>
                            <th>Latitude</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.dealers.api.table') }}",
                                "columns": [
                          {data: 'code', name: 'code'},
                          {data: 'dealer', name: 'dealer'},
                                    {data: 'city', name: 'city'},
                                    {data: 'country', name: 'countries.country', searchable: false},
                                    {data: 'longitude', name: 'countries.longitude', searchable: false},
                                    {data: 'latitude', name: 'countries.latitdue', searchable: false},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>

@stop

@section("script")
    <script type="text/javascript">
        $(document).ready(function () {
            //Filter toggle
            $('.filter .panel-heading').click(function () {
                $(this).closest('.panel').toggleClass('up');
            });

            $("#btn-reset").click(function () {
                var appendDiv = jQuery($(".condition:last")[0].outerHTML);
                $(".condition").remove();
                $("#filters").prepend(appendDiv.attr('id', '0'));
                $("#0").find('select').val('0');
                $("#0").find('input[type=text]').val('');
            });

            //Add condition
            $('.add-condition').click(function () {
                var id = $(".condition:last").attr('id');
                var appendDiv = jQuery($(".condition:last")[0].outerHTML);

                appendDiv.attr('id', ++id).insertAfter(".condition:last");

                $("#" + id).find('select').val('0');
                $("#" + id).find('input[type=text]').val('');

                return false;
            });

        });
    </script>
@stop

resources/views/dealers/map.blade.php
@extends("dcms::template/layout")

@section("content")
    <div class="main-header">
        <h1>Dealers</h1>
        <ol class="breadcrumb">
            <li><a href="{{ URL::to('admin/dashboard') }}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li><a href="{{ URL::to('admin/dealers') }}"><i class="far fa-map-marker-alt"></i> Dealers</a></li>
            <li class="active"><i class="far fa-map"></i> Map</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">
                    <h2>Filter</h2>
                    {!! Form::open(array('url' => 'admin/dealers/map')) !!}

                    <div class="form-group">
                        {!! Form::label('search_id', 'Search (Dealer, Address, City)') !!}
                        {!! Form::text('search', request()->get('search'), array('class' => 'form-control')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('country_id', 'Country') !!}
                        {!! Form::select('country_id', array('0'=>'-','1' => 'Belgium', '2' => 'Netherlands', '3' => 'France', '4' => 'Germany'),request()->get('country_id'), array('class' => 'form-control')) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::submit('Set filter', array('class' => 'btn btn-primary')) !!}
                        <a href="{!! URL::previous() !!}" class="btn btn-default">Reset filter</a>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
            <div class="col-md-12">
                <div class="main-content-block no-padding">
                    <div id="dealermap"></div>
                </div>
            </div>
        </div>
    </div>
@stop

@section("script")
    <?php
    /*
    ini_set('error_reporting', E_ALL);
    ini_set('display_errors', '1');
    */

    $minZoom = 12; //'a better name would be maxZoom - 12 has been defined as highest zoom, (20 is maximum, but not relevant) 12-08-2010


    //$latitude = $minLatitude + ($difLatitude/2);
    //$longitude = $minLongitude + ($difLongitude/2);
    ?>

    <script>

        function initMap() {

            var initCenter = new google.maps.LatLng(50.56318, 4.69528);
            var initZoom = 7;

            var map = new google.maps.Map(document.getElementById('dealermap'), {
                zoom: initZoom,
                center: initCenter
            });
            var bounds = new google.maps.LatLngBounds();

            var dealers = [
                {!!$mapMarkers!!}
            ];

            var iconBase = '/packages/Dcms/dealers/images/marker/';
            var icons = {
                'default': {url: iconBase + 'default.svg', scaledSize: new google.maps.Size(28, 34)},
                'extended': {url: iconBase + 'extended.svg', scaledSize: new google.maps.Size(28, 34)},
                'premium': {url: iconBase + 'premium.svg', scaledSize: new google.maps.Size(28, 34)},
            };

            var infowindow = new google.maps.InfoWindow();

            dealers.forEach(function (dealer) {

                var marker = new google.maps.Marker({
                    position: dealer.position,
                    icon: icons[dealer.type],
                    map: map,
                    zIndex: dealer.zindex,
                    optimized: false,
                });

                bounds.extend(dealer.position);
                map.fitBounds(bounds);

                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.close();
                    infowindow.setContent(dealer.info);
                    infowindow.open(map, marker);
                });
            });

            var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function (event) {
                google.maps.event.removeListener(boundsListener);
            });
        }
    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ env("BROWSER_GOOGLE_MAPS_KEY") }}&callback=initMap"></script>

@stop